apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::528010887209:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1PI19KI05E0Z2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::528010887209:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T11:46:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1520"
  uid: 343b6c59-690e-428c-8656-13daf2dde839
